name: Main

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5"

jobs:

  scalafmt:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          apps: scalafmt
      - uses: coursier/cache-action@v3
      - run:  scalafmt --check

  example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          apps: mill
      - uses: coursier/cache-action@v3
      - run:  mill '__.{one,two}'
